#%RAML 1.0
title: Iataaa
version: v1.0
mediaType: application/json
documentation :
- title : Home
  content: Web platform which manages draught game beetween web services.

uses:
  PlayerLibrary : types/playerLibrary.raml
  GameLibrary : types/gameLibrary.raml
  ResponseLibrary : types/responseLibrary.raml

/api/games : !include endpoints/games.raml
/api/players : !include endpoints/players.raml
